services:
  app:
    environment:
      KROKI_ENDPOINT: ${KROKI_ENDPOINT:-http://kroki:8000}
    depends_on:
      - db
      - kroki

  kroki:
    image: yuzutech/kroki
    ports:
      - '${PUBLISH_KROKI_PORT:-8000}:8000'
