import type { ScreenshotScenario, ScreenshotViewport } from "../app/frontend/screenshot_audit"

export const desktopViewport: ScreenshotViewport = {
  name: "desktop",
  width: Number.parseInt(process.env.SCREENSHOT_WIDTH ?? "1440", 10),
  height: Number.parseInt(process.env.SCREENSHOT_HEIGHT ?? "900", 10),
}

export const explicitScreenshotScenarios: readonly ScreenshotScenario[] = [
  // === 認証 ===
  {
    id: "session.new.guest.desktop",
    screenName: "ログイン",
    userStory: "未ログインの利用者がメールアドレスとパスワードを入力してポータルへ進む",
    url: "/session/new",
    urlRule: "static",
    httpMethod: "GET",
    role: "guest",
    viewport: desktopViewport,
    prerequisites: ["未認証のブラウザーセッション"],
    actions: [],
    stateKind: "default",
    execution: "capture",
    expectedSelectors: ["form", "input[type='email']", "input[type='password']"],
    expectedState: { description: "ログインフォームが入力可能", selector: "form" },
    outputName: "session-new",
    expectedBehavior: ["メールアドレスとパスワードを入力してログイン"],
  },

  // === 管理画面ダッシュボード ===
  {
    id: "admin-dashboard.index.admin.desktop",
    screenName: "管理ダッシュボード",
    userStory: "管理者が管理画面トップで全体状況を確認する",
    url: "/admin",
    urlRule: "static",
    httpMethod: "GET",
    role: "admin",
    viewport: desktopViewport,
    prerequisites: ["管理者でログイン済み", "標準seedデータを投入済み"],
    actions: [],
    stateKind: "default",
    execution: "capture",
    expectedSelectors: ["main"],
    expectedState: { description: "管理ダッシュボードが表示済み", selector: ".admin-header" },
    outputName: "admin-dashboard",
    expectedBehavior: [
      "要対応事項の確認",
      "各管理機能への導線",
    ],
  },

  // === 公開側ダッシュボード ===
  {
    id: "dashboard.show.external.desktop",
    screenName: "利用者ダッシュボード",
    userStory: "外部利用者がアクセス可能な案件と文書を確認する",
    url: "/dashboard",
    urlRule: "static",
    httpMethod: "GET",
    role: "external",
    viewport: desktopViewport,
    prerequisites: ["外部利用者でログイン済み"],
    actions: [],
    stateKind: "default",
    execution: "deferred",
    deferral: {
      reason: "撮影環境に外部利用者の認証情報がまだない",
      resumeCondition: "SCREENSHOT_EXTERNAL_EMAILとSCREENSHOT_EXTERNAL_PASSWORDを環境変数に登録する",
    },
    expectedSelectors: ["main"],
    expectedState: { description: "利用者ダッシュボードが表示済み", selector: "main" },
    outputName: "dashboard-external",
    expectedBehavior: [
      "アクセス可能な案件の一覧確認",
      "最近閲覧した文書へのアクセス",
      "お気に入り・後で読むショートカット",
    ],
  },

  // === 管理 - 文書マスタ ===
  {
    id: "admin-documents.index.admin.desktop",
    screenName: "文書マスタ一覧",
    userStory: "管理者が文書マスタを検索・フィルタして対象文書を確認する",
    url: "/admin/documents",
    urlRule: "static",
    httpMethod: "GET",
    role: "admin",
    viewport: desktopViewport,
    prerequisites: ["管理者でログイン済み", "標準seedデータを投入済み"],
    actions: [],
    stateKind: "default",
    execution: "capture",
    expectedSelectors: ["main"],
    expectedState: { description: "文書一覧テーブルが表示済み", selector: ".admin-header" },
    outputName: "admin-documents-index",
    expectedBehavior: [
      "案件・状態・種別による検索とフィルタ",
      "列設定のカスタマイズ",
      "CSV出力",
      "文書のアーカイブ・復元操作",
    ],
  },

  // === 管理 - 案件 ===
  {
    id: "admin-projects.index.admin.desktop",
    screenName: "案件一覧",
    userStory: "管理者が案件を検索・管理する",
    url: "/admin/projects",
    urlRule: "static",
    httpMethod: "GET",
    role: "admin",
    viewport: desktopViewport,
    prerequisites: ["管理者でログイン済み", "標準seedデータを投入済み"],
    actions: [],
    stateKind: "default",
    execution: "capture",
    expectedSelectors: ["main"],
    expectedState: { description: "案件一覧テーブルが表示済み", selector: ".admin-header" },
    outputName: "admin-projects-index",
    expectedBehavior: [
      "会社・案件名による検索",
      "案件の新規作成・編集",
    ],
  },

  // === 管理 - 文書権限 ===
  {
    id: "admin-document-permissions.index.admin.desktop",
    screenName: "文書権限一覧",
    userStory: "管理者が文書権限の付与状況を確認・管理する",
    url: "/admin/document_permissions",
    urlRule: "static",
    httpMethod: "GET",
    role: "admin",
    viewport: desktopViewport,
    prerequisites: ["管理者でログイン済み", "標準seedデータを投入済み"],
    actions: [],
    stateKind: "default",
    execution: "capture",
    expectedSelectors: ["main"],
    expectedState: { description: "文書権限一覧が表示済み", selector: ".admin-header" },
    outputName: "admin-document-permissions-index",
    expectedBehavior: [
      "案件・文書・会社・ユーザーによるフィルタ",
      "権限の追加・変更・削除",
      "CSV出力",
    ],
  },

  // === 管理 - 文書セット ===
  {
    id: "admin-document-sets.index.admin.desktop",
    screenName: "文書セット一覧",
    userStory: "管理者が文書セットを確認・管理する",
    url: "/admin/document_sets",
    urlRule: "static",
    httpMethod: "GET",
    role: "admin",
    viewport: desktopViewport,
    prerequisites: ["管理者でログイン済み", "標準seedデータを投入済み"],
    actions: [],
    stateKind: "default",
    execution: "capture",
    expectedSelectors: ["main"],
    expectedState: { description: "文書セット一覧が表示済み", selector: ".admin-header" },
    outputName: "admin-document-sets-index",
    expectedBehavior: [
      "文書セットの作成・編集・削除",
      "対象文書の管理（固定版 / 最新版）",
    ],
  },

  // === 管理 - Git連携 ===
  {
    id: "admin-git-import-sources.index.admin.desktop",
    screenName: "Git連携設定一覧",
    userStory: "管理者がGit連携ソースの設定状況と同期履歴を確認する",
    url: "/admin/git_import_sources",
    urlRule: "static",
    httpMethod: "GET",
    role: "admin",
    viewport: desktopViewport,
    prerequisites: ["管理者でログイン済み", "標準seedデータを投入済み"],
    actions: [],
    stateKind: "default",
    execution: "capture",
    expectedSelectors: ["main"],
    expectedState: { description: "Git連携設定一覧が表示済み", selector: ".admin-header" },
    outputName: "admin-git-import-sources-index",
    expectedBehavior: [
      "連携設定の追加・編集・削除",
      "手動同期の実行",
    ],
  },

  // === 管理 - 外部フォルダ同期 ===
  {
    id: "admin-external-folder-sync-sources.index.admin.desktop",
    screenName: "外部フォルダ同期設定一覧",
    userStory: "管理者が外部フォルダ同期ソースの設定状況を確認する",
    url: "/admin/external_folder_sync_sources",
    urlRule: "static",
    httpMethod: "GET",
    role: "admin",
    viewport: desktopViewport,
    prerequisites: ["管理者でログイン済み", "標準seedデータを投入済み"],
    actions: [],
    stateKind: "default",
    execution: "capture",
    expectedSelectors: ["main"],
    expectedState: { description: "外部フォルダ同期設定一覧が表示済み", selector: ".admin-header" },
    outputName: "admin-external-folder-sync-sources-index",
    expectedBehavior: [
      "Google Drive / SharePoint 同期設定の管理",
      "dry-run → レビュー → 適用のフロー",
      "OAuth接続・Webhook購読の管理",
    ],
  },

  // === 管理 - Webhook ===
  {
    id: "admin-webhook-endpoints.index.admin.desktop",
    screenName: "Webhook設定一覧",
    userStory: "管理者がWebhook通知先の設定と送信状況を確認する",
    url: "/admin/webhook_endpoints",
    urlRule: "static",
    httpMethod: "GET",
    role: "admin",
    viewport: desktopViewport,
    prerequisites: ["管理者でログイン済み", "標準seedデータを投入済み"],
    actions: [],
    stateKind: "default",
    execution: "capture",
    expectedSelectors: ["main"],
    expectedState: { description: "Webhook設定一覧が表示済み", selector: ".admin-header" },
    outputName: "admin-webhook-endpoints-index",
    expectedBehavior: [
      "Webhookエンドポイントの追加・編集・削除",
      "イベント種別の設定",
    ],
  },

  // === 管理 - アクセスログ ===
  {
    id: "admin-access-logs.index.admin.desktop",
    screenName: "アクセスログ",
    userStory: "管理者がポータルへのアクセス履歴を監査する",
    url: "/admin/access_logs",
    urlRule: "static",
    httpMethod: "GET",
    role: "admin",
    viewport: desktopViewport,
    prerequisites: ["管理者でログイン済み", "標準seedデータを投入済み"],
    actions: [],
    stateKind: "default",
    execution: "capture",
    expectedSelectors: ["main"],
    expectedState: { description: "アクセスログ一覧が表示済み", selector: ".admin-header" },
    outputName: "admin-access-logs-index",
    expectedBehavior: [
      "ユーザー・案件・会社・日付によるフィルタ",
      "CSV出力",
    ],
  },

  // === 公開側 - 文書ツリー ===
  {
    id: "projects.show.external.desktop",
    screenName: "案件文書ツリー",
    userStory: "外部利用者が案件内の文書ツリーから目的の文書を探す",
    url: "/projects/:code",
    urlRule: "dynamic",
    httpMethod: "GET",
    role: "external",
    viewport: desktopViewport,
    prerequisites: ["外部利用者でログイン済み", "閲覧権限のある案件が存在"],
    actions: [],
    stateKind: "default",
    execution: "deferred",
    deferral: {
      reason: "動的な案件codeが必要。撮影スクリプトがseed案件を特定して撮影する",
      resumeCondition: "外部利用者の認証情報と閲覧可能案件をseedに追加する",
    },
    expectedSelectors: ["[data-docs-sidebar]", "main"],
    expectedState: { description: "文書ツリーとコンテンツが表示済み", selector: "[data-docs-sidebar]" },
    outputName: "projects-show-tree",
    expectedBehavior: [
      "文書ツリーの展開・折りたたみ",
      "文書の選択と本文表示",
      "サイドバーのリサイズ・折りたたみ",
    ],
  },

  // === 管理 - 診断 ===
  {
    id: "admin-diagnostics.index.admin.desktop",
    screenName: "診断",
    userStory: "管理者がシステム構成と要対応事項を診断する",
    url: "/admin/diagnostics",
    urlRule: "static",
    httpMethod: "GET",
    role: "admin",
    viewport: desktopViewport,
    prerequisites: ["管理者でログイン済み"],
    actions: [],
    stateKind: "default",
    execution: "capture",
    expectedSelectors: ["main"],
    expectedState: { description: "診断画面が表示済み", selector: ".admin-header" },
    outputName: "admin-diagnostics-index",
    expectedBehavior: [
      "環境設定の整合性確認",
      "要対応事項の確認と対処導線",
    ],
  },
]
