class AddJapaneseNameCommentsToTablesAndColumns < ActiveRecord::Migration[8.1]
  TABLE_COMMENTS = {
    access_logs: "アクセスログ",
    access_requests: "アクセス申請",
    bulk_edit_dry_runs: "一括編集ドライラン",
    companies: "会社",
    consent_terms: "同意規約",
    document_approval_requests: "文書承認依頼",
    document_bookmarks: "文書ブックマーク",
    document_catalog_items: "文書カタログ項目",
    document_catalogs: "文書カタログ",
    document_delivery_logs: "文書送付ログ",
    document_files: "文書ファイル",
    document_keywords: "文書キーワード",
    document_permissions: "文書権限",
    document_relations: "文書関連",
    document_review_comments: "文書レビューコメント",
    document_set_items: "文書セット項目",
    document_sets: "文書セット",
    document_taggings: "文書タグ付け",
    document_tags: "文書タグ",
    document_versions: "文書バージョン",
    documents: "文書",
    external_folder_sync_items: "外部フォルダ同期項目",
    external_folder_sync_runs: "外部フォルダ同期実行",
    external_folder_sync_sources: "外部フォルダ同期元",
    external_folder_sync_subscriptions: "外部フォルダ同期購読",
    external_folder_sync_webhook_events: "外部フォルダ同期Webhookイベント",
    git_import_runs: "Git取り込み実行",
    git_import_sources: "Git取り込み元",
    import_dry_runs: "取り込みドライラン",
    import_route_settings: "取り込みルート設定",
    microsoft_graph_connections: "Microsoft Graph接続",
    notification_events: "通知イベント",
    notification_receipts: "通知受信",
    project_consent_settings: "案件同意設定",
    project_memberships: "案件メンバー",
    projects: "案件",
    publish_jobs: "公開ジョブ",
    read_confirmations: "既読確認",
    solid_cable_messages: "Solid Cableメッセージ",
    tree_view_states: "ツリー表示状態",
    user_consents: "利用者同意",
    users: "利用者",
    webhook_deliveries: "Webhook配信",
    webhook_endpoints: "Webhookエンドポイント"
  }.freeze

  COLUMN_COMMENTS = {
    access_level: "アクセス権限",
    accessed_at: "アクセス日時",
    active: "有効フラグ",
    actor_user_id: "実行者ID",
    action_type: "操作種別",
    acted_by_id: "対応者ID",
    approved_at: "承認日時",
    approver_id: "承認者ID",
    archived_at: "アーカイブ日時",
    archived_by_user_id: "アーカイブ実行者ID",
    artifact_path: "成果物パス",
    audience_type: "対象者種別",
    auth_config: "認証設定",
    auth_type: "認証種別",
    author_id: "投稿者ID",
    bcc_addresses: "BCCアドレス",
    body: "本文",
    bookmark_type: "ブックマーク種別",
    branch: "ブランチ",
    callback_url: "コールバックURL",
    cancelled_at: "キャンセル日時",
    category: "カテゴリ",
    cc_addresses: "CCアドレス",
    changelog_summary: "変更概要",
    channel: "チャンネル",
    channel_hash: "チャンネルハッシュ",
    checksum: "チェックサム",
    client_id: "クライアントID",
    client_secret: "クライアントシークレット",
    code: "コード",
    comment_type: "コメント種別",
    commit_sha: "コミットSHA",
    company_id: "会社ID",
    confirmed_at: "確認日時",
    confirmed_by_id: "確認者ID",
    conflict_policy: "競合方針",
    consent_scope: "同意範囲",
    consent_term_id: "同意規約ID",
    consent_term_version_label: "同意規約バージョンラベル",
    consented_at: "同意日時",
    content_type: "コンテンツ種別",
    created_at: "作成日時",
    created_by_id: "作成者ID",
    credential_ref: "認証情報参照",
    credential_secret: "認証情報シークレット",
    cursor: "カーソル",
    delivery_type: "送付種別",
    description: "説明",
    discard_candidate_at: "廃棄候補日時",
    document_catalog_id: "文書カタログID",
    document_file_id: "文書ファイルID",
    document_id: "文書ID",
    document_kind: "文書種別",
    document_set_id: "文書セットID",
    document_tag_id: "文書タグID",
    document_version_id: "文書バージョンID",
    domain: "ドメイン",
    drive_id: "ドライブID",
    email_address: "メールアドレス",
    enabled: "有効フラグ",
    error_message: "エラーメッセージ",
    errors_count: "エラー数",
    errors_json: "エラーJSON",
    event_key: "イベントキー",
    event_type: "イベント種別",
    event_types: "イベント種別一覧",
    expanded_keys: "展開キー一覧",
    expires_at: "有効期限日時",
    external_folder_id: "外部フォルダID",
    external_folder_path: "外部フォルダパス",
    external_folder_sync_source_id: "外部フォルダ同期元ID",
    external_folder_sync_subscription_id: "外部フォルダ同期購読ID",
    external_item_id: "外部項目ID",
    external_modified_at: "外部更新日時",
    external_parent_id: "外部親ID",
    file_name: "ファイル名",
    file_size: "ファイルサイズ",
    finished_at: "終了日時",
    folder_url: "フォルダURL",
    git_import_source_id: "Git取り込み元ID",
    headers_json: "ヘッダーJSON",
    id: "ID",
    import_mode: "取り込みモード",
    importance_level: "重要度",
    installation_id: "インストールID",
    internal_only: "社内限定フラグ",
    ip_address: "IPアドレス",
    items_created_count: "作成項目数",
    items_deleted_count: "削除項目数",
    items_scanned_count: "走査項目数",
    items_skipped_count: "スキップ項目数",
    items_updated_count: "更新項目数",
    keyword: "キーワード",
    last_error_message: "最終エラーメッセージ",
    last_login_at: "最終ログイン日時",
    last_renewed_at: "最終更新日時",
    last_synced_at: "最終同期日時",
    last_synced_commit_sha: "最終同期コミットSHA",
    latest_version_id: "最新バージョンID",
    log_message: "ログメッセージ",
    markdown_entry_path: "Markdownエントリーパス",
    mime_type: "MIMEタイプ",
    mode: "実行モード",
    name: "名称",
    normalized_keyword: "正規化キーワード",
    normalized_name: "正規化名称",
    note: "備考",
    notes: "備考",
    notification_event_id: "通知イベントID",
    occurred_at: "発生日時",
    operation_type: "操作種別",
    organization_name: "組織名",
    owner_id: "所有者ID",
    owner_type: "所有者種別",
    parent_id: "親コメントID",
    params_json: "パラメータJSON",
    password_digest: "パスワードダイジェスト",
    path: "パス",
    payload: "ペイロード",
    payload_json: "ペイロードJSON",
    pdf_snapshot_path: "PDFスナップショットパス",
    portal_modified_at: "ポータル更新日時",
    preview_folder_path: "プレビューフォルダパス",
    project_id: "案件ID",
    provider: "プロバイダー",
    provider_channel_id: "プロバイダーチャンネルID",
    provider_metadata: "プロバイダーメタデータ",
    provider_resource_id: "プロバイダーリソースID",
    provider_subscription_id: "プロバイダー購読ID",
    public_id: "公開ID",
    published_at: "公開日時",
    published_by_user_id: "公開者ID",
    published_from: "公開開始日時",
    published_until: "公開終了日時",
    read_at: "既読日時",
    reading_note: "読了メモ",
    reason: "申請理由",
    received_at: "受信日時",
    recommended_sort_order: "推奨表示順",
    rejected_at: "却下日時",
    rejection_reason: "却下理由",
    relation_type: "関連種別",
    repository_full_name: "リポジトリ完全名",
    request_body: "リクエスト本文",
    requestable_id: "申請対象ID",
    requestable_type: "申請対象種別",
    requested_access_level: "申請アクセス権限",
    requester_id: "申請者ID",
    required_on: "要求対象",
    requirement_timing: "要求タイミング",
    resolved_at: "解決日時",
    resolved_by_id: "解決者ID",
    response_body: "レスポンス本文",
    response_status: "レスポンスステータス",
    result_json: "結果JSON",
    retention_until: "保存期限日時",
    role: "役割",
    route_key: "ルートキー",
    scan_error_message: "スキャンエラーメッセージ",
    scan_status: "スキャンステータス",
    scanned_at: "スキャン日時",
    search_body_text: "検索本文",
    search_text: "検索テキスト",
    secret_token: "シークレットトークン",
    sender_id: "送信者ID",
    sent_at: "送信日時",
    set_type: "セット種別",
    setting_key: "設定キー",
    setting_value: "設定値",
    site_build_path: "サイトビルドパス",
    site_id: "サイトID",
    size: "サイズ",
    slug: "スラッグ",
    snapshot_kind: "スナップショット種別",
    sort_order: "表示順",
    source_basename: "ソースベース名",
    source_branch: "ソースブランチ",
    source_commit_hash: "ソースコミットハッシュ",
    source_directory: "ソースディレクトリ",
    source_extension: "ソース拡張子",
    source_file_name: "ソースファイル名",
    source_path: "ソースパス",
    source_relative_path: "ソース相対パス",
    source_repo: "ソースリポジトリ",
    source_document_id: "元文書ID",
    started_at: "開始日時",
    status: "ステータス",
    storage_key: "ストレージキー",
    subject: "件名",
    summary_json: "サマリーJSON",
    sync_direction: "同期方向",
    sync_status: "同期ステータス",
    target_document_id: "先文書ID",
    target_id: "対象ID",
    target_name: "対象名",
    target_type: "対象種別",
    target_url: "送信先URL",
    target_document_ids: "対象文書ID一覧",
    tenant_id: "テナントID",
    text_anchor_label: "テキストアンカーラベル",
    text_anchor_path: "テキストアンカーパス",
    text_anchor_type: "テキストアンカー種別",
    text_line_end: "終了行",
    text_line_start: "開始行",
    title: "タイトル",
    to_addresses: "宛先アドレス",
    tree_instance_key: "ツリーインスタンスキー",
    updated_at: "更新日時",
    user_agent: "ユーザーエージェント",
    user_id: "利用者ID",
    user_type: "利用者種別",
    verification_token_digest: "検証トークンダイジェスト",
    version_label: "バージョンラベル",
    visibility_policy: "公開方針",
    warnings_json: "警告JSON",
    webhook_endpoint_id: "WebhookエンドポイントID"
  }.freeze

  TABLE_SPECIFIC_COLUMN_COMMENTS = {
    companies: { name: "会社名" },
    projects: { code: "案件コード", name: "案件名" },
    users: { name: "氏名" }
  }.freeze

  def up
    TABLE_COMMENTS.each do |table_name, comment|
      change_table_comment table_name, comment
    end

    TABLE_COMMENTS.each_key do |table_name|
      connection.columns(table_name).each do |column|
        change_column_comment table_name, column.name, column_comment_for(table_name, column.name)
      end
    end
  end

  def down
    raise ActiveRecord::IrreversibleMigration
  end

  private

  def column_comment_for(table_name, column_name)
    column_key = column_name.to_sym
    TABLE_SPECIFIC_COLUMN_COMMENTS.dig(table_name, column_key) ||
      COLUMN_COMMENTS.fetch(column_key) do
        raise ArgumentError, "Missing Japanese comment for #{table_name}.#{column_name}"
      end
  end
end
