require "pathname"
require "yaml"

require_relative "../artifact"

module GeneratedFiles
  module Generators
    class AiUsecaseDecisionFlow
      DEFAULT_SOURCE = "storage/document_files/external_samples/ai-usecases/AI活用手順ポータル/data/decision_flow.yml"
      DEFAULT_MARKDOWN = "storage/document_files/external_samples/ai-usecases/AI活用手順ポータル/decision-flow.md"
      DEFAULT_PLANTUML = "docs/ai-usecases/generated/decision-flow.puml"

      def initialize(
        source_path: DEFAULT_SOURCE,
        markdown_path: DEFAULT_MARKDOWN,
        plantuml_path: DEFAULT_PLANTUML,
        diagram_language: nil,
        root: nil
      )
        @root = Pathname(root || default_root).expand_path
        @source_path = absolute_path(source_path)
        @markdown_path = Pathname(markdown_path)
        @plantuml_path = Pathname(plantuml_path)
        @diagram_language = diagram_language
        @data = YAML.safe_load(@source_path.read, permitted_classes: [], aliases: false)
      end

      def call
        validate!
        [
          GeneratedFiles::Artifact.new(
            path: relative_output_path(@markdown_path),
            content: markdown,
            content_type: "text/markdown"
          ),
          GeneratedFiles::Artifact.new(
            path: relative_output_path(@plantuml_path),
            content: plantuml,
            content_type: "text/vnd.plantuml"
          )
        ]
      end

      private

      attr_reader :root

      def default_root
        if defined?(Rails)
          Rails.root
        else
          Pathname(__dir__).join("..", "..", "..", "..").expand_path
        end
      end

      def flow = @data.fetch("flow")
      def questions = @data.fetch("questions")
      def results = @data.fetch("results")
      def rule_table = @data.fetch("rule_table", [])

      def validate!
        questions.each do |id, question|
          question.fetch("text")
          [branch_target(question, "yes"), branch_target(question, "no")].each do |target|
            next if questions.key?(target) || results.key?(target)

            raise KeyError, "#{id} points to unknown target: #{target}"
          end
        end
      end

      def markdown
        language = @diagram_language || ENV.fetch("AI_USECASE_FLOW_DIAGRAM_LANGUAGE", flow.fetch("default_diagram_language", "text"))
        <<~MARKDOWN
          ---
          title: #{flow.fetch("title")}
          ---

          # #{flow.fetch("title")}

          <!-- GENERATED FROM #{relative(@source_path)}. DO NOT EDIT THIS FILE DIRECTLY. -->

          #{flow.fetch("description")}

          ## まず確認すること

          #{question_table}

          ## 推奨手順一覧

          #{result_table}

          ## PlantUMLソース

          以下は `#{relative(@source_path)}` から生成されたPlantUMLです。Kroki連携環境で図として表示したい場合は、環境変数 `AI_USECASE_FLOW_DIAGRAM_LANGUAGE=plantuml` を指定して再生成します。

          ```#{language}
          #{plantuml}
          ```

          ## ルール表

          #{rules_markdown_table}

          ## 更新方法

          1. `#{relative(@source_path)}` を変更する。
          2. `bin/rails ai_usecases:generate_flow` を実行する。
          3. `#{relative_output_path(@markdown_path)}` と `#{relative_output_path(@plantuml_path)}` の差分を確認する。
          4. `rails db:seed` でdocs-portalに取り込む。
        MARKDOWN
      end

      def question_table
        rows = questions.map do |id, question|
          [id, question.fetch("text"), target_label(branch_target(question, "yes")), target_label(branch_target(question, "no"))]
        end
        table(%w[NodeID 判断項目 Yes No], rows)
      end

      def result_table
        rows = results.map do |_id, result|
          link = "[#{result.fetch("procedure_id")}](#{result.fetch("href")})"
          [link, result.fetch("title"), result.fetch("tool"), result.fetch("pattern"), result.fetch("description")]
        end
        table(%w[手順ID 手順名 AIツール PatternID 説明], rows)
      end

      def rules_markdown_table
        rows = rule_table.map do |rule|
          [rule.fetch("rule_id"), rule.fetch("priority"), rule.fetch("condition"), rule.fetch("pattern"), rule.fetch("tool"), rule.fetch("procedure")]
        end
        table(%w[RuleID 優先度 条件 推奨PatternID 推奨ToolID 推奨手順ID], rows)
      end

      def plantuml
        lines = ["@startuml", "start", ":#{escape_puml(flow.fetch("entry_label"))};"]
        emit_node(lines, "start", 0)
        lines << "stop"
        lines << "@enduml"
        lines.join("\n")
      end

      def emit_node(lines, node_id, depth)
        if results.key?(node_id)
          result = results.fetch(node_id)
          lines << "  " * depth + ":#{escape_puml(result.fetch("procedure_id"))}\\n#{escape_puml(result.fetch("title"))};"
          return
        end

        question = questions.fetch(node_id)
        indent = "  " * depth
        lines << "#{indent}if (#{escape_puml(question.fetch("text"))}) then (Yes)"
        emit_node(lines, branch_target(question, "yes"), depth + 1)
        lines << "#{indent}else (No)"
        emit_node(lines, branch_target(question, "no"), depth + 1)
        lines << "#{indent}endif"
      end

      def branch_target(question, key)
        return question.fetch(key) if question.key?(key)

        yaml_boolean_key = key == "yes" ? true : false
        question.fetch(yaml_boolean_key)
      end

      def target_label(target)
        if results.key?(target)
          result = results.fetch(target)
          "#{result.fetch("procedure_id")} #{result.fetch("title")}"
        else
          questions.fetch(target).fetch("text")
        end
      end

      def table(headers, rows)
        ([headers, headers.map { "---" }] + rows).map do |row|
          "| #{row.map { cell(_1) }.join(" | ")} |"
        end.join("\n")
      end

      def cell(value)
        value.to_s.gsub("|", "\\|").gsub("\n", "<br>")
      end

      def escape_puml(value)
        value.to_s.gsub("\n", "\\n").gsub(":" , "：")
      end

      def relative(path)
        Pathname(path).relative_path_from(root).to_s
      end

      def relative_output_path(path)
        path = Pathname(path)
        path.absolute? ? relative(path) : path.cleanpath.to_s
      end

      def absolute_path(path)
        path = Pathname(path)
        path.absolute? ? path : root.join(path)
      end
    end
  end
end
